@apiKey=JEXqpyi4cPGWgH
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4NWM4ZTk1ZC1jMWQ4LTRlODAtYWYwMC1mNjQ1ODk2MDI3NjQiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGVkdWFyZG9sYWIuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDA0MDQ3NzksImV4cCI6MTc0MTAwOTU3OSwiaWF0IjoxNzQwNDA0Nzc5fQ.MIuZn0q3D7sYf1wnjI0PCvCcJftZ8lkNCci-eRt0z4k

# Get all
GET {{HostAddress}}/{{Path}}
Authorization: Bearer {{token}}
Accept: application/json

### get by id

GET {{HostAddress}}/{{Path}}/ad73ec52-0974-4198-810e-4840e1ad195a
Authorization: Bearer {{token}}
Accept: application/json

### create

POST {{HostAddress}}/{{Path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "UserId": "85C8E95D-C1D8-4E80-AF00-F64589602764",
  "ArticleId": "6D70CA49-8EC2-4383-9FF6-B7AF43A1192D"
}