@apiKey=JEXqpyi4cPGWgH
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMTk2MTBmNS0wZDdlLTc1YWUtOWJiNy02ZmI3ZjYwYjFmNTIiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGVkdWFyZG9sYWIuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDQzMTI3NDcsImV4cCI6MTc0NDkxNzU0NywiaWF0IjoxNzQ0MzEyNzQ3fQ.x_bscHQy9NvetekmDVvrc6Z2b0v_UNasaYS83vGIFPY

### Get paginated

GET {{HostAddress}}/{{ArticlesPath}}?pageNumber=1&pageSize=10
Accept: application/json
X-Api-Key: {{apiKey}}

### get by id

GET {{HostAddress}}/{{ArticlesPath}}/0195c351-2ab5-78ba-bd2a-0ac915dc5f4f
Accept: application/json
X-Api-Key: {{apiKey}}
Authorization: Bearer {{token}}


### create article

POST {{HostAddress}}/{{ArticlesPath}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Test2",
    "subtitle": "test2",
    "text": "text22",
    "categoryid": "0195c34c-0b24-7f1d-b502-e7bee888734e",
    "thumbnailid": "0195c34c-0b46-79e1-ae55-cf8fe370ff17"
}

### update article

PUT {{HostAddress}}/{{ArticlesPath}}/01963f07-ef24-7049-b9d0-ee7b898be9c7
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "title": "Title update2",
    "subtitle": "subtitle update2",
    "text": "text update 2",
    "categoryid": "0195c34c-0b24-7f1d-b502-e7bee888734e",
    "thumbnailid": "0195c34c-0b46-79e1-ae55-cf8fe370ff17"
}

### delete article (logically)

DELETE {{HostAddress}}/{{ArticlesPath}}/01961b2a-6783-7cb2-bb59-cc5185f6fef0
Authorization: Bearer {{token}}
Content-Type: application/json

###

GET https://localhost:7190/api/articles

###

GET {{HostAddress}}/{{ArticlesPath}}
Accept: application/json

###

@hostname=localhost
@port=7190
@host={{hostname}}:{{port}}
GET https://{{host}}/api/articles