@apiKey=JEXqpyi4cPGWgH
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2M2M1YjE0ZS02MDdiLTQwMTYtODM1OC02YTM1ZWE5NmMwNWUiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGVkdWFyZG9sYWIuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDIyMDg2MzYsImV4cCI6MTc0MjgxMzQzNiwiaWF0IjoxNzQyMjA4NjM2fQ.fkgrpkjNmG4HItInIvFEa6vmVTLdfV8awKvu_8SXoa0

### Get paginated

GET {{HostAddress}}/{{ArticlesPath}}?pageNumber=1&pageSize=3
Accept: application/json
X-Api-Key: {{apiKey}}

### get by id

GET {{HostAddress}}/{{ArticlesPath}}/ad73ec52-0974-4198-810e-4840e1ad195a
Accept: application/json
X-Api-Key: {{apiKey}}

### create article

POST {{HostAddress}}/{{ArticlesPath}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Test1",
    "subtitle": "test1",
    "text": "text",
    "categoryid": "0195a3aa-ab0f-72e5-864a-ceacda58a5c1",
    "thumbnailid": "0195a3aa-ab35-78a3-90ea-c90b4668e35e"
}

### update article

PUT {{HostAddress}}/{{ArticlesPath}}/ad73ec52-0974-4198-810e-4840e1ad195a
Content-Type: application/json
{
    "title": "Title update2",
    "subtitle": "subtitle update2",
    "text": "text update 2",
    "categoryid": "803C62B1-C1CA-4C9B-BDB8-7DA7485283D9",
    "colorid": "0DE1AECF-3217-4AF5-87D7-0B48F5322022",
    "thumbnailid": "48AA27CA-2EAF-4CBD-B744-B84F045E066D"
}

### delete article (logically)

DELETE {{HostAddress}}/{{ArticlesPath}}/ad73ec52-0974-4198-810e-4840e1ad195a
Content-Type: application/json

###

GET https://localhost:7190/api/articles

###

GET {{HostAddress}}/{{ArticlesPath}}
Accept: application/json

###

@hostname=localhost
@port=7190
@host={{hostname}}:{{port}}
GET https://{{host}}/api/articles