@apiKey=JEXqpyi4cPGWgH
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMTk2NWY0OS00ZDNmLTcyMzQtYmQ0Yy1jOGY5ZDA4Y2RiNGIiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGVkdWFyZG9sYWIuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDcyMTE1ODgsImV4cCI6MTc0NzgxNjM4OCwiaWF0IjoxNzQ3MjExNTg4fQ.2bTtZnjuROcUcPSrsXJNVysBE2zB1sCDzJK7v7jSSeE

### Get paginated

GET {{HostAddress}}/{{ArticlesPath}}?pageNumber=1&pageSize=10
Accept: application/json
X-Api-Key: {{apiKey}}
Authorization: Bearer {{token}}

### Search

GET {{HostAddress}}/{{ArticlesPath}}/Search?Query=news
Accept: application/json
X-Api-Key: {{apiKey}}

### get by id

GET {{HostAddress}}/{{ArticlesPath}}/0196584f-2594-7c8a-86b7-ff0672d16265
Accept: application/json
X-Api-Key: {{apiKey}}
Authorization: Bearer {{token}}


### create article

POST {{HostAddress}}/{{ArticlesPath}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "SOLID Design Pattern",
    "subtitle": "How to use SOLID",
    "text": "blah blah blah",
    "categoryid": "01965f47-83be-768c-9137-382637d67c85",
    "thumbnailid": "01965f47-83db-7f38-bce5-8c1b8e44ce4a"
}

### update article

PUT {{HostAddress}}/{{ArticlesPath}}/01963f07-ef24-7049-b9d0-ee7b898be9c7
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "title": "Title update2",
    "subtitle": "subtitle update2",
    "text": "text update 2",
    "categoryid": "0195c34c-0b24-7f1d-b502-e7bee888734e",
    "thumbnailid": "0195c34c-0b46-79e1-ae55-cf8fe370ff17"
}

### delete article (logically)

DELETE {{HostAddress}}/{{ArticlesPath}}/01961b2a-6783-7cb2-bb59-cc5185f6fef0
Authorization: Bearer {{token}}
Content-Type: application/json

###

GET https://localhost:7190/api/articles

###

GET {{HostAddress}}/{{ArticlesPath}}
Accept: application/json

###

@hostname=localhost
@port=7190
@host={{hostname}}:{{port}}
GET https://{{host}}/api/articles