@apiKey=JEXqpyi4cPGWgH
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMTk2MTBmNS0wZDdlLTc1YWUtOWJiNy02ZmI3ZjYwYjFmNTIiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGVkdWFyZG9sYWIuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDQ5OTY3NTksImV4cCI6MTc0NTYwMTU1OSwiaWF0IjoxNzQ0OTk2NzU5fQ.pGlOAZkOHGCKALX-jq7mFQ5JZ5EoxY810DGINrp37As

# Get all from authenticated user
GET {{HostAddress}}/{{BookmarksPath}}
Authorization: Bearer {{token}}
Accept: application/json

### create

POST {{HostAddress}}/{{BookmarksPath}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ArticleId": "01962595-c90f-7078-a9fd-c71dab80cbce"
}

### delete

DELETE {{HostAddress}}/{{BookmarksPath}}/01963f1a-26ce-7656-b961-31e5ac6bdcd3
Authorization: Bearer {{token}}
Content-Type: application/json