@apiKey=JEXqpyi4cPGWgH

### login

POST {{HostAddress}}/{{IdentityPath}}/login
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "email": "admin@eduardolab.com",
  "password": "0DE1AECF-3217-4AF5-87D7-0B48F5322022"
}

### Get all
GET {{HostAddress}}/{{IdentityPath}}
Accept: application/json
X-Api-Key: {{apiKey}}

### get by id

GET {{HostAddress}}/{{IdentityPath}}/85c8e95d-c1d8-4e80-af00-f64589602764
Accept: application/json
X-Api-Key: {{apiKey}}

### register Admin

POST {{HostAddress}}/{{IdentityPath}}/Register
X-Api-Key: JEXqpyi4cPGWgH
Content-Type: application/json
{
    "FirstName": "Admin",
    "MiddleName": "",
    "Surname": "Admin",
    "email": "admin@eduardolab.com",
    "password": "0DE1AECF-3217-4AF5-87D7-0B48F5322022",
    "ConfirmPassword": "0DE1AECF-3217-4AF5-87D7-0B48F5322022",
    "Role": 1
}

### register User

POST {{HostAddress}}/{{IdentityPath}}/Register
X-Api-Key: JEXqpyi4cPGWgH
Content-Type: application/json

{
    "FirstName": "Test",
    "MiddleName": "",
    "Surname": "Test",
    "email": "test@test.com",
    "password": "1q",
    "ConfirmPassword": "1q2w3e4r",
    "Role": 2
}