global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'articlecatalog_api'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:6087']