@apiKey=JEXqpyi4cPGWgH
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4NWM4ZTk1ZC1jMWQ4LTRlODAtYWYwMC1mNjQ1ODk2MDI3NjQiLCJ1bmlxdWVfbmFtZSI6ImFkbWluQGVkdWFyZG9sYWIuY29tIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE3NDA0MDQ3NzksImV4cCI6MTc0MTAwOTU3OSwiaWF0IjoxNzQwNDA0Nzc5fQ.MIuZn0q3D7sYf1wnjI0PCvCcJftZ8lkNCci-eRt0z4k

GET {{HostAddress}}/{{Path}}?pageNumber=2&pageSize=1
Accept: application/json
X-Api-Key: {{apiKey}}

### get by id

GET {{HostAddress}}/{{Path}}/ad73ec52-0974-4198-810e-4840e1ad195a
Accept: application/json
X-Api-Key: {{apiKey}}

### create article

POST {{HostAddress}}/{{Path}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Test6",
    "subtitle": "test6",
    "text": "text",
    "categoryid": "803C62B1-C1CA-4C9B-BDB8-7DA7485283D9",
    "colorid": "0DE1AECF-3217-4AF5-87D7-0B48F5322022",
    "thumbnailid": "48AA27CA-2EAF-4CBD-B744-B84F045E066D"
}

### update article

PUT {{HostAddress}}/{{Path}}/ad73ec52-0974-4198-810e-4840e1ad195a
Content-Type: application/json
{
    "title": "Title update2",
    "subtitle": "subtitle update2",
    "text": "text update 2",
    "categoryid": "803C62B1-C1CA-4C9B-BDB8-7DA7485283D9",
    "colorid": "0DE1AECF-3217-4AF5-87D7-0B48F5322022",
    "thumbnailid": "48AA27CA-2EAF-4CBD-B744-B84F045E066D"
}

### delete article (logically)

DELETE {{HostAddress}}/{{Path}}/ad73ec52-0974-4198-810e-4840e1ad195a
Content-Type: application/json

###

GET https://localhost:7190/api/articles

###

GET {{HostAddress}}/{{Path}}
Accept: application/json

###

@hostname=localhost
@port=7190
@host={{hostname}}:{{port}}
GET https://{{host}}/api/articles