@apiKey=JEXqpyi4cPGWgH

# Get all
GET {{HostAddress}}/{{Path}}
Accept: application/json
X-Api-Key: {{apiKey}}

### get by id

GET {{HostAddress}}/{{Path}}/ad73ec52-0974-4198-810e-4840e1ad195a
Accept: application/json
X-Api-Key: {{apiKey}}